language: go

go:
  - '1.12'

before_deploy:
  - zip -r "eventreplay-${TRAVIS_TAG}.zip" dist/*

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: bs17l+IJXibH/cdjDgwcKC8ijdM0MTaERse9+DLdFcibzVcCeUYiZmH48R1gDHIXEFsCrr+EVpDdlG+0tJnqaYxjwkwJ7GpAIRSfrXDWEqhAc/jxa/KLCW2cYmmFY86JXJhQOrJtaeVRNlNIO0AcuKE5kIbHdCQc8mTqjcVYpR41LpvrJb/tsbl3pwsqCi+ubolQEHIBdB0GbrP+iEmalg29u/wMfqx2EL0soURpf3iYT2fISWQYfRUr0UgFxz3Uf6DRFSoMThTt4HOQ8if6H3fFb2bjLBbignoo8yZSdcYK/tcvuZhNNeHlxYCnCb1DgRmCW9ySsWPX62OtBk62AH6roEU5UertCHYbfQgXLtO+Ed/T618Eu6s+Ppp2yp5t/a5kP7QRbapJi73G1GczUZLhdhDQEmq/YAb0TpgYMJUcukn9UMq3ezNZCcky35DmDixVh64Ub5FIPAVwUrx86XCivTpKjkiQbC0Hoj8ecACd3HxBIP9opKheIMUp3xXsPWdL5TPe9FCY10PQuDZ4q6kZ9DbXrPVO9aQJCmjYv6jSoOAVMVvyDuN8s3InNIWwmMinE34qTSIvOrS8l2YtJ4i1XEzeD3ckpx/80IoofCvgjK4ZQBunhFd4aR4fhg+zKM9N4lejII/0MqTMYPXSftZOQguaf3D1cDeQrXiJAZ4=
  file: eventreplay-*.zip
  file_glob: true
  on:
    tags: true