language: go

go:
  - '1.12'

before_deploy:
  - zip -r "eventreplay-${TRAVIS_TAG}.zip" dist/*

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: s+0o2xsDk43HKgV6/xw/KL/C4CtQP/hnZjRtDI4O3D3krtzrqfULtREX5pRpfic594Titu1ocaWLepSzwOrlCrd9lrfwzWL6UNqVhYsVhhKP84dUDfXRT+TpLg/6URWHurjOQjPlapoD1GHizX8/v1bBa8Et6yr+klyhuguoCMLQmNYbiZzED1ZuKG1B2H1PtLIZN0JZtaNF/lnNsRdZV9IekNadw5Bv4eDBaWHbZFxykaH5lpml+7ILsAk4/bXaPOYHj4U/TE9KCLG9hRChKBZBaFIfNNfT7mI8GGhd4AsBHvOHQwvcDlm849lm6VsltyJm4jYpryL7RzpMYZyRsPRkFNR7tXSBBHYoYZc+2zHVRx3/RAbntZhosH3qfvyamF8lrQ8Knxq8XO4B+AhLfMQ8z9aSdqJThbZCzKLzAhcL1zMfXqcbx8O5RNBVEHbbU4kY2KjRx30OGKzzir+NZ0+rXNSTFZ+wTTt4RpwypwoGI713qM4WpXPKfud2vAyYoNurN+paIdg3AR7qs+W7ZPuULi904fEYpYKvrdlzQbH9zg2V+PBRku1AFp1S3Le42eRGHZHlg9fbSH6kC9Mu3yzMjNDCGqOc5VpsdZpEbXWONOyMxlshjIh3xoKTvvD6lV286t2c05ba2EQAzJ2hUX86+bol0DzYsjCYplSYDJw=
  file: eventreplay-*.zip
  file_glob: true
  on:
    tags: true